# Generated by Django 5.2.10 on 2026-01-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_productcolorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ceiling', 'Ceiling Fan'), ('Pedestal', 'Pedestal Fan'), ('Wall', 'Wall Fan'), ('Table', 'Table Fan'), ('Exhaust', 'Exhaust Fan')], max_length=20),
        ),
    ]
