# Generated by Django 5.2.10 on 2026-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_warrantyregistration_warrantyapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyregistration',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
