# Generated by Django 5.2.10 on 2026-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_image_alter_productcolorimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyregistration',
            name='product_name',
            field=models.CharField(choices=[('Nano Premium 1200mm ', 'Nano Premium 1200mm '), ('Nano Premium 900mm', 'Nano Premium 900mm'), ('Breeza 1200mm', 'Breeza 1200mm'), ('Dume 1200mm', 'Dume 1200mm'), ('Dume Led', 'Dume Led')], max_length=50),
        ),
    ]
