# Generated by Django 5.2.10 on 2026-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Ceiling', 'Ceiling Fan'), ('Wall', 'Wall Fan'), ('Table', 'Table Fan'), ('Exhaust', 'Exhaust Fan')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
