# Generated by Django 5.2.10 on 2026-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ceiling', 'Ceiling Fan')], max_length=20),
        ),
    ]
