# Generated by Django 5.2.10 on 2026-02-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('Maavel', 'Maavel'), ('Atmos Pro', 'Atmos Pro'), ('Spin Air', 'Spin Air'), ('Atmos Silent', 'Atmos Silent'), ('Max Air', 'Max Air'), ('Dazzale', 'Dazzale')], max_length=50)),
                ('product_color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Brown', 'Brown'), ('Ivory', 'Ivory')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('date_of_purchase', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.warrantyregistration')),
            ],
        ),
    ]
